// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Vth7Fk4GJ16jAFBhYbQHuvsNZ4cmgPA',
    appId: '1:180964838386:web:134c57515250b73c76396b',
    messagingSenderId: '180964838386',
    projectId: 'skillswap-7fd3a',
    authDomain: 'skillswap-7fd3a.firebaseapp.com',
    storageBucket: 'skillswap-7fd3a.firebasestorage.app',
    measurementId: 'G-ZQ7Z1W7EPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBlo78ge7k8JKGzgzybSruthT4J69gKZg',
    appId: '1:180964838386:android:8dcc7d229f9f713c76396b',
    messagingSenderId: '180964838386',
    projectId: 'skillswap-7fd3a',
    storageBucket: 'skillswap-7fd3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWSPVWL0kj8fGNZa4bfogxZznF9IsM3a8',
    appId: '1:180964838386:ios:affdc06fb4caaae476396b',
    messagingSenderId: '180964838386',
    projectId: 'skillswap-7fd3a',
    storageBucket: 'skillswap-7fd3a.firebasestorage.app',
    androidClientId: '180964838386-8mgka93d1qfvsgdaemogbc2iidek9n6f.apps.googleusercontent.com',
    iosClientId: '180964838386-csu0uhhqeee69i3esd931llhdedlpv7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourOwnProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWSPVWL0kj8fGNZa4bfogxZznF9IsM3a8',
    appId: '1:180964838386:ios:affdc06fb4caaae476396b',
    messagingSenderId: '180964838386',
    projectId: 'skillswap-7fd3a',
    storageBucket: 'skillswap-7fd3a.firebasestorage.app',
    androidClientId: '180964838386-8mgka93d1qfvsgdaemogbc2iidek9n6f.apps.googleusercontent.com',
    iosClientId: '180964838386-csu0uhhqeee69i3esd931llhdedlpv7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourOwnProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Vth7Fk4GJ16jAFBhYbQHuvsNZ4cmgPA',
    appId: '1:180964838386:web:e1452a579110101876396b',
    messagingSenderId: '180964838386',
    projectId: 'skillswap-7fd3a',
    authDomain: 'skillswap-7fd3a.firebaseapp.com',
    storageBucket: 'skillswap-7fd3a.firebasestorage.app',
    measurementId: 'G-Y7EYM5B6RH',
  );
}
